### ISSUE TITLE
quitar info de debug

### ISSUE THREAD

**Issue by ftoledo** [HuayraLinux/rtl-8723-dkms#1]
quitar info de debug del modulo 8723be

<pre>
[  768.230234] RTL871X: rtl8723b_c2h_packet_handler: C2H, ID=3 seq=99 len=8
[  768.238798] RTL871X: rtl8723b_c2h_packet_handler: C2H, ID=3 seq=100 len=8
[  770.215311] RTL871X: IsBtDisabled=0, IsBtControlLps=0
[  772.223578] RTL871X: IsBtDisabled=0, IsBtControlLps=0
[  774.231605] RTL871X: IsBtDisabled=0, IsBtControlLps=0
[  776.239706] RTL871X: IsBtDisabled=0, IsBtControlLps=0
[  778.247867] RTL871X: IsBtDisabled=0, IsBtControlLps=0
[  780.256087] RTL871X: IsBtDisabled=0, IsBtControlLps=0
[  782.264138] RTL871X: IsBtDisabled=0, IsBtControlLps=0
[  784.272373] RTL871X: IsBtDisabled=0, IsBtControlLps=0
[  784.273103] RTL871X: SetHwReg8723B(wlan0): [HW_VAR_MACID_WAKEUP] macid=0, org reg_0x4d4=0x00000000
[  784.281764] RTL871X: rtl8723b_c2h_packet_handler: C2H, ID=3 seq=101 len=8
[  784.286624] RTL871X: rtl8723b_c2h_packet_handler: C2H, ID=3 seq=102 len=8
[  786.280333] RTL871X: IsBtDisabled=0, IsBtControlLps=0
[  788.288498] RTL871X: IsBtDisabled=0, IsBtControlLps=0
[  790.296630] RTL871X: IsBtDisabled=0, IsBtControlLps=0
[  792.304730] RTL871X: IsBtDisabled=0, IsBtControlLps=0
[  794.312772] RTL871X: IsBtDisabled=0, IsBtControlLps=0
[  796.321030] RTL871X: IsBtDisabled=0, IsBtControlLps=0
[  798.329224] RTL871X: IsBtDisabled=0, IsBtControlLps=0
[  800.337421] RTL871X: IsBtDisabled=0, IsBtControlLps=0
[  800.337993] RTL871X: SetHwReg8723B(wlan0): [HW_VAR_MACID_WAKEUP] macid=0, org reg_0x4d4=0x00000000
[  800.343244] RTL871X: rtl8723b_c2h_packet_handler: C2H, ID=3 seq=103 len=8
[  802.345331] RTL871X: IsBtDisabled=0, IsBtControlLps=0
[  804.353483] RTL871X: IsBtDisabled=0, IsBtControlLps=0
[  806.361951] RTL871X: IsBtDisabled=0, IsBtControlLps=0
[ 
</pre>

**Comment by matiasdelellis** [comment]
Toledooo.. VA CA CI O NESSSSSS!!..  :sweat_smile:

**Comment by matiasdelellis** [comment]
Wii.. Closeeeeee.. :wink:

**Comment by ftoledo** [comment]
Acabas de arreglar el bug mas molesto de todos.
